api/urls.py
from django.urls import path

from api.shops.views import ShopView, ScrappperView
from api.users.views import UserlistView, SuppliersView
from api.settings.views import LogsView
from api.membership_pricing.views import MembershipPricingView
from api.views import FaqView, QueriesView

urlpatterns = [
    path('shop/', ShopView.as_view(), name='api_shop'),
    path('shop/scrapper/', ScrappperView.as_view(), name='api_shop_scrapper'),
    path('users/', UserlistView.as_view(), name='api_users'),
    path('suppliers/', SuppliersView.as_view(), name='api_suppliers'),
    path('logs/', LogsView.as_view(), name='api_logs'),
    path('memship_pricing/', MembershipPricingView.as_view(), name='api_memship_pricing'),
    path('faq/', FaqView.as_view(), name='api_faq'),
    path('queries/', QueriesView.as_view(), name='api_queries'),
]

app/backend/urls.py
from django.urls import path

from app.backend.views import sign_in, dashboard, registration, list_of_shop, update_shop, list_of_users, \
    reported_product, list_of_suppliers, logs_history, sign_out, list_of_shop_scrapper, update_shop_scrapper, gen_info, \
    upload_logo_photo, upload_shoplogo, view_users, assigned_user_roles, deactivate_users, activate_users, \
    reset_password, \
    membership_pricing, update_membership_pricing, faq_admin, update_faq, queries, view_queries

urlpatterns = [
    path('', sign_in, name='sign_in'),
    path('sign-out/', sign_out, name='sign_out'),
    path('dashboard/', dashboard, name='dashboard'),
    path('registration/', registration, name='registration'),
    path('shop/scrapper/', list_of_shop_scrapper, name='list_of_shop_scrapper'),
    path('shop/update/scrapper/<int:pk>', update_shop_scrapper, name='update_shop_scrapper'),
    path('shop/list/', list_of_shop, name='list_of_shop'),
    path('shop/update/<int:pk>', update_shop, name='update_shop'),
    path('users/list/', list_of_users, name='list_of_users'),
    path('update-users-list/<int:pk>', view_users, name='view_users'),
    path('assigned-users-roles/<int:pk>', assigned_user_roles, name='assigned_user_roles'),
    path('deactivate_users/', deactivate_users, name='deactivate_users'),
    path('activate_users/', activate_users, name='activate_users'),
    path('reset_password/<int:user_id>', reset_password, name='reset_password'),
    path('reported_product/', reported_product, name='reported_product'),
    path('list_of_suppliers/', list_of_suppliers, name='list_of_suppliers'),
    path('logs_history/', logs_history, name='logs_history'),
    path('general-information/', gen_info, name='gen_info'),
    path('update-system-logo/<int:pk>', upload_logo_photo, name='upload_logo_photo'),
    path('update-shops-logo/<int:pk>', upload_shoplogo, name='upload_shoplogo'),
    path('membership/pricing/', membership_pricing, name='membership_pricing'),
    path('update/membership/pricing/<int:pk>', update_membership_pricing, name='update_membership_pricing'),
    path('frequently-ask-questions/', faq_admin, name='faq_admin'),
    path('update/frequently-ask-questions/<int:pk>', update_faq, name='update_faq'),
    path('queries/', queries, name='queries'),
    path('view/queries/<int:pk>', view_queries, name='view_queries'),
    #    path('activate_user/<uidb64>/<token>', activate_user, name='activate'),
]

rcstockv2/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from app.cron.in_stock_notif import in_stock_notif
from app.paypal import views
from app.paypal.views import process_payment
from app.views import landing, autocomplete_suggestions, about, data_protection, \
    login_user, logout_user, contact_us, user_dashboard, user_changepassword, \
    user_account, affiliate, market_intelligence, product_click, get_in_stock, get_all_stock, search_results_v2, \
    process_search_results_v2, user_market_intelligence_dashboard, user_market_intelligence_shops, \
    faq, notify_me, subscribe_free, price_development
from rcstockv2 import settings

urlpatterns = [
    path('', landing, name='landing'),
    path('login/', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('contact/', contact_us, name='contact_us'),
    path('user/dashboard/', user_dashboard, name='user_dashboard'),
    path('user/market-intelligence/dashboard/', user_market_intelligence_dashboard,
       name='user_market_intelligence_dashboard'),
    path('user/market-intelligence/shop/<int:pk>/<int:owner_id>', user_market_intelligence_shops,
       name='user_market_intelligence_shops'),
    path('user/changepassword/', user_changepassword, name='user_changepassword'),
    path('user/account/', user_account, name='user_account'),
    path('autocomplete/', autocomplete_suggestions, name='autocomplete_suggestions'),
    path('shop/search/results/process/<str:search_input>/<int:pk>/<int:beta_search>',
       process_search_results_v2,
       name='process_search_results'),
    path('shop/search/results/<str:search_input>/<int:pk>/<int:beta_search>', search_results_v2,
       name='search_results'),
    path('shop/products/notify/', in_stock_notif, name='in_stock_notif'),
    path('shop/search/results/process/in-stock/<str:search_input>/<int:pk>/<int:beta_search>',
       get_in_stock,
       name='get_in_stock'),
    path('shop/search/results/process/all-stock/<str:search_input>/<int:pk>/<int:beta_search>',
       get_all_stock,
       name='get_all_stock'),
    path('shop/product/click/<int:pk>', product_click, name='product_click'),
    path('about/', about, name='about'),
    path('affiliate/', affiliate, name='affiliate'),
    path('frequently-ask-questions/', faq, name='faq'),
    path('market_intelligence/', market_intelligence, name='market_intelligence'),
    # path('subscribe-paypal/<int:pk>/<int:user_id>', subscribe_paypal, name='subscribe_paypal'),
    path('data/protection/', data_protection, name='data_protection'),
    path('rc-admin/', include('app.backend.urls')),
    path('api/', include('api.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('paypal/subscribe/<int:pk>/<int:user_id>', process_payment, name='subscribe_paypal'),
    path('paypal/subscribe/success/', views.payment_done, name='payment_done'),
    path('paypal/subscribe/cancelled/', views.payment_canceled, name='payment_cancelled'),
    path('shop/product/notify/', notify_me, name='notify_me'),
    path('subscribe/free/', subscribe_free, name='subscribe_free'),
    path('price/development/<str:prod_name>', price_development, name='price_development'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/backend/models.py
from django.db import models
from django.utils import timezone

from app.models import AuthUser


class TblFaq(models.Model):
    id = models.BigAutoField(primary_key=True)
    question = models.TextField(blank=True, null=True)
    answer = models.TextField(blank=True, null=True)
    link = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(AuthUser, models.DO_NOTHING)
    isactive = models.SmallIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tbl_faq'


class TblPriceDevelopment(models.Model):
    id = models.BigAutoField(primary_key=True)
    product_name = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tbl_price_development'


class TblSubPriceDevelopment(models.Model):
    id = models.BigAutoField(primary_key=True)
    prod = models.ForeignKey(TblPriceDevelopment, models.DO_NOTHING)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True, default=timezone.now)

    class Meta:
        managed = False
        db_table = 'tbl_sub_price_development'


class TblMembershipPricing(models.Model):
    id = models.BigAutoField(primary_key=True)
    membership_type = models.CharField(max_length=255, blank=True, null=True)
    duration = models.IntegerField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    services = models.TextField(blank=True, null=True)
    is_active = models.IntegerField(blank=True, null=True)
    uploaded_by = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'tbl_membership_pricing'


class TblSubscription(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    membership = models.ForeignKey(TblMembershipPricing, models.DO_NOTHING)
    created_at = models.DateTimeField(blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    invoice = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tbl_subscription'


class TblGeneralInfo(models.Model):
    id = models.IntegerField(primary_key=True)
    system_name = models.CharField(max_length=255, blank=True, null=True)
    system_version = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    mobile_no = models.CharField(max_length=255, blank=True, null=True)
    fax = models.CharField(max_length=255, blank=True, null=True)
    tel_no = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    picture = models.FileField(upload_to='rcstockv_logo/')
    about = models.TextField(blank=True, null=True)
    data_protection = models.TextField(blank=True, null=True)
    affiliate = models.TextField(blank=True, null=True)
    market_intelligence = models.TextField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True, default=timezone.now)
    updatedby = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        db_table = 'tbl_general_info'


class Loghistory(models.Model):
    id = models.BigAutoField(primary_key=True)
    descriptions = models.CharField(max_length=255, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    datetime_added = models.DateTimeField(blank=True, null=True, default=timezone.now)

    class Meta:
        managed = False
        db_table = 'tbl_loghistory'


class Supplier(models.Model):
    id = models.IntegerField(primary_key=True)
    company_name = models.CharField(max_length=255, blank=True, null=True)
    contact = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)
    fax = models.CharField(max_length=255, blank=True, null=True)
    home_page = models.CharField(max_length=255, blank=True, null=True)
    status = models.BooleanField(blank=True, null=True)
    date_create = models.DateTimeField(blank=True, null=True, default=timezone.now)

    class Meta:
        managed = False
        db_table = 'tbl_supplier'

class TblContactUs(models.Model):
    id = models.BigAutoField(primary_key=True)
    fullname = models.CharField(max_length=255, blank=True, null=True)
    email = models.CharField(max_length=255, blank=True, null=True)
    subject = models.CharField(max_length=255, blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    is_seen = models.SmallIntegerField(blank=True, null=True)
    is_reply = models.SmallIntegerField(blank=True, null=True)
    date_added = models.DateTimeField(blank=True, null=True, default=timezone.now)

    class Meta:
        managed = False
        db_table = 'tbl_contact_us'

class TblContactUsReply(models.Model):
    id = models.BigAutoField(primary_key=True)
    query = models.ForeignKey(TblContactUs, models.DO_NOTHING)
    replied_by = models.ForeignKey(AuthUser, models.DO_NOTHING)
    message = models.TextField(blank=True, null=True)
    datetime_added = models.DateTimeField(blank=True, null=True, default=timezone.now)

    class Meta:
        managed = False
        db_table = 'tbl_contact_us_reply'

app/backend/forms.py
from django import forms

from app.backend.models import TblGeneralInfo
from app.models import Shop


class UploadLogoForm(forms.ModelForm):
    class Meta:
        model = TblGeneralInfo
        fields = ['picture']


class UploadShopLogoForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ['logo']

api/membership_pricing/views.py
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated

from app.backend.models import Loghistory, TblMembershipPricing
from api.settings.serializers import LogsSerializer
from api.membership_pricing.serializers import MembershipSerializer


class MembershipPricingView(generics.ListAPIView):
	queryset = TblMembershipPricing.objects.all().order_by('-price')
	serializer_class = MembershipSerializer
	permission_classes = [IsAuthenticated]

templates/backend/assigned_user_roles.html
{% load tags %}
<div class="row">
	<form id="submitroleForm">
		{% csrf_token %}
	   	<div class="modal-body">
			<div class="mb-3">
				<label>Role <span class="asteriskField">*</span></label>
				<select class="form-select select2" id="up_permission" name="up_permission" required>
					<option></option>
					{% for row in permission %}
						{% if row.id == user_permission.permission_id %}
							<option value="{{ row.id }}" selected>{{ row.name }}</option>
						{% else %}
							<option value="{{ row.id }}">{{ row.name }}</option>
						{% endif %}
					{% endfor %}
				</select>
			</div>
	    </div>
	    <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
	        <button type="submit" class="btn btn-primary">Save changes</button>
	    </div>
	</form>
</div>
<script type="text/javascript">
	$('.select2').select2({
		width: '100%',
		theme: 'bootstrap-5',
	    placeholder: 'Choose',
	    dropdownParent: $('#assigned_roles')
	});

	$('#submitroleForm').on('submit', function(e){
		var form = new FormData(this);
		e.preventDefault();
        Swal.fire({
            title: "Are you sure",
            text: "You want to update user role?",
            icon: "info",
            showCancelButton: true,
            confirmButtonText: "Yes",
            allowOutsideClick: false,
            showLoaderOnConfirm: true,
            preConfirm: function (){
                return $.post({
                    url: "{% url 'assigned_user_roles' pk %}",
                    data: form,
                    success : function (response){
                        if(response.data == "success"){
                            Swal.fire({
                                title: "Good job!",
                                html:  response.msg,
                                icon: "success",
                                allowOutsideClick: false,
                            }).then((result) => {
                                if (result.isConfirmed){
                                    $('#submitroleForm').trigger('reset');
                                    $('#user_list').DataTable().ajax.reload();
                                    $('#close-role').click();
                                }
                            });
                        }else{
                        	Swal.fire({
                        		title: "Oops!",
                                html:  response.msg,
                                icon: "error",
                                allowOutsideClick: false,
                        	});
                        }
                    },
                    cache       : false,
                    contentType : false,
                    processData : false,
                });
            },
        });
	});
</script>

templates/backend/general_information.html
{% extends 'backend/layout.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="row mt-5 align-items-center justify-content-between">
	    <div class="col-auto">
            <h3 class="app-page-title mb-0">Settings</h3>
	    </div>
    </div>
	<br><br>
	<div class="col-sm-12 row">
		<div class="app-card app-card-orders-table shadow-sm mb-5">
		    <div class="app-card-body">
		    	<div class="row">
		    		<div class="col-sm-4">
		    			<img src="{{ gen_info.picture.url }}" style="object-fit:cover;" id="profile-avatar" class="rounded-circle" width="300px" height="300px" style="color: black;">
				        <button type="button" class="btn btn-primary btn-rounded" id="btn-update-picture" style="margin-top: 120px !important; margin-left: -40px;">
				        	<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-camera"viewBox="0 0 16 16">
							  	<path d="M15 12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h1.172a3 3 0 0 0 2.12-.879l.83-.828A1 1 0 0 1 6.827 3h2.344a1 1 0 0 1 .707.293l.828.828A3 3 0 0 0 12.828 5H14a1 1 0 0 1 1 1v6zM2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2z"/>
							  	<path d="M8 11a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5zm0 1a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM3 6.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
							</svg>
				        </button>
				        <form id="uploadPhotoForm" enctype="multipart/form-data" style="display: none;">
				            {% csrf_token %}
				            <div class="form-group">
				            	{{ uploadlogo_form.picture|as_crispy_field }}
				            </div>
				            <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Save changes</button>
				        </form>
				        <br><br>
			    	</div>
			    	<div class="col-sm-8">
			    		<form id="submitEditForm">
			    			{% csrf_token %}
			    			<input type="hidden" name="gen_id" value="{{gen_info.id}}">
			    			<div class="mb-3">
								<label>System Name <span class="asteriskField">*</span></label>
								<input  name="sys_name" type="text" class="form-control sys_name" placeholder="System Name" required="required" value="{{gen_info.system_name}}">
							</div>
							<div class="mb-3">
								<label>System Version<span class="asteriskField">*</span></label>
								<input  name="system_ver" type="text" class="form-control system_ver" placeholder="System Version" required="required" value="{{gen_info.system_version}}">
							</div>
							<div class="mb-3">
								<label>Email <span class="asteriskField">*</span></label>
								<input  name="email" type="text" class="form-control email" placeholder="Email" required="required" value="{{gen_info.email}}">
							</div>
							<div class="mb-3">
								<label>Address <span class="asteriskField">*</span></label>
								<input  name="address" type="text" class="form-control address" placeholder="Address" required="required" value="{{gen_info.address}}">
							</div>
							<div class="row">
								<div class="mb-3 col-sm-4">
									<label>Mobile No.</label>
									<input  name="mob_no" type="text" class="form-control mob_no" placeholder="0000000000" value="{{gen_info.mobile_no}}">
								</div>
								<div class="mb-3 col-sm-4">
									<label>Tel No.</label>
									<input  name="tel_no" type="text" class="form-control tel_no" placeholder="00000000" value="{{gen_info.tel_no}}">
								</div>
								<div class="mb-3 col-sm-4">
									<label>Fax</label>
									<input  name="fax" type="text" class="form-control fax" placeholder="00000000" value="{{gen_info.fax}}">
								</div>
							</div>
							<div class="mb-3">
								<label>Data Protection <span class="asteriskField">*</span></label>
								<textarea class="form-control summernote" name="data_protection" style="height: 200px;">{{gen_info.data_protection}}</textarea>
							</div>
							<div class="mb-3">
								<label>Affiliate <span class="asteriskField">*</span></label>
								<textarea class="form-control summernote" name="affiliate" style="height: 200px;">{{gen_info.affiliate}}</textarea>
							</div>
							<div class="mb-3">
								<label>Market Intelligence <span class="asteriskField">*</span></label>
								<textarea class="form-control summernote" name="market_intelligence" style="height: 200px;">{{gen_info.market_intelligence}}</textarea>
							</div>
							<button type="submit" class="btn btn-primary mt-3 float-end mb-3">Save changes</button>
			    		</form>
			    	</div>
		    	</div>
		    </div>	
		</div>
	</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
	$(document).ready(function() {

		 $('.summernote').summernote({
	        height: $(window).height() * 0.7,
	        dialogsInBody: true,
	        fontSizeUnits: ['px', 'pt'],
	        dialogsFade: true,
	        codeviewFilterRegex: 'custom-regex',
	        disableDragAndDrop: true,
	        toolbar: [
	          ['style', ['style']],
	          ['font', ['bold', 'underline', 'clear']],
	          ['color', ['color']],
	          ['para', ['ul', 'ol', 'paragraph']],
	          ['table', ['table']],
	          ['insert', ['link', 'picture', 'video']],
	          ['view', ['fullscreen', 'codeview', 'help']]
	        ]
	    });

		 $('#id_picture').on('change', function(){
            readURLPhoto(this);
        });

        function readURLPhoto(input) {
            var url = input.value;
            var ext = url.substring(url.lastIndexOf('.') + 1).toLowerCase();
            if (input.files && input.files[0]&& (ext == "gif" || ext == "png" || ext == "jpeg" || ext == "jpg")) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#profile-avatar').attr('src', e.target.result);
                }
                $('#uploadPhotoForm').submit();
                reader.readAsDataURL(input.files[0]);
            }
        }

        $('#btn-update-picture').on('click', function(){
            $('#id_picture').trigger('click');
        });

        $('#uploadPhotoForm').on('submit', function(e){
	        $.ajax({
	            data        : new FormData(this),
	            url         : '{% url "upload_logo_photo" gen_info.id %}',
	            type        : 'POST',
	            cache       : false,
	            contentType : false,
	            processData : false
	        })
	        .done(function(response){
	             if(response) {
	             	$('#header-profile').attr('src', response.picture);
	                $("#profile-avatar").attr("src", response.picture);
	                toastr.success(response.msg, "Success!", {timeOut: 2000});
	            }
	        });
	        e.preventDefault();
	    });
	});

 


     $('#submitEditForm').on('submit', function(e){
        var form = new FormData(this);
        Swal.fire({
            title: "Are you sure",
            text: "You want to edit the System Generail Information",
            icon: "info",
            showCancelButton: true,
            confirmButtonText: "Yes",
            allowOutsideClick: false,
            showLoaderOnConfirm: true,
            preConfirm: function (){
                return $.post({
                    url: "{% url 'gen_info' %}",
                    data: form,
                    success : function (response){
                        if(response.data == "success"){
                            toastr.success(response.msg, "Success!", {timeOut: 2000});
                        }
                    },
                    cache       : false,
                    contentType : false,
                    processData : false,
                });
            },
        });
        e.preventDefault();
    });
</script>
{% endblock %}

templates/backend/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en"> 
<head>
    <title>RCStock | Login</title>
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'backend/assets/libs/textSpinner/spinner.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
</head> 

<body>
	<div class="d-lg-flex half">
		<div class="bg order-1 order-md-2" style="background-image:url({% static 'img/login-background.jpg' %})"></div>
		<div class="contents order-2 order-md-1">
			<div class="container">
				<div class="row align-items-center justify-content-center">
					<div class="col-md-7">
						<img src="{% static 'img/logo-colored.png' %}" width="50%"><br><br>
                        <div class="alertDiv"></div>
						<form id="loginForm">
							{% csrf_token %}
							<div class="form-group mb-3">
								<label for="username">Username</label>
								<input type="text" class="form-control" name="username" placeholder="Your Username" id="username">
							</div>
							<div class="form-group mb-3">
								<label for="password">Password</label>
								<input type="password" class="form-control" name="password" placeholder="Your Password" id="password">
							</div>
							<script src='https://www.google.com/recaptcha/api.js'></script>
                            <div class="g-recaptcha" data-sitekey="6LeYSAYiAAAAALQZns8j5Qw1gTYZ-iR61gcHSc6u"></div>
                            <br>
							<div class="d-flex mb-5 align-items-center">
								<span class="ml-auto">
									<a href="#" class="forgot-pass">Forgot Password</a>
								</span>
							</div>
							<div class="d-grid gap-2">
								<button type="submit" class="btn btn-primary w-100 theme-btn mx-auto" type="submit">
                                    <span class="spinner-border spinner-border-sm" role="status" id="loader" style="display:none" aria-hidden="true"></span> 
                                    Sign In
                                </button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script>
        $(document).ready(function(){
            $('#loginForm').on('submit', function(e){
                var form = new FormData(this);
                $.ajax({
                    data        : form,
                    url         : '{% url "sign_in" %}',
                    type        : 'POST',
                    beforeSend: function(){
                        $('.sign-in-text').text("");
                        $('.btn').attr('disabled', 'true');
                        $('#loader').css('display', '');
                    },
                    success: function(response){
                        if(response.data){
                            window.location.href = "{% if request.GET.next %}{{ request.GET.next }}{% else %}{% url 'dashboard' %}{% endif %}";
                        }else{
                            $('.sign-in-text').text("Sign In");
                            grecaptcha.reset();
                            $('.btn').removeAttr('disabled');
                            $('#loader').css('display', 'none');
                            $('.alertDiv').html('<div class="alert alert-dismissible alert-danger">' +
                                            '<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>' +
                                            '<i class="bx bx-info-circle"></i> &nbsp;' + response.msg + '</div>');
                        }
                    },
                    cache       : false,
                    contentType : false,
                    processData : false,

                });
                e.preventDefault();
            });
        });
    </script>
</body>
</html> 